code review required:
- changed-files:
  - any-glob-to-any-file: '**'

approved:
- pull-request-review-state: approved

hotfix:
 - head-branch: ['^hotfix', 'hotfix']
feature:
 - head-branch: ['^feature', 'feature']
bug:
 - head-branch: ['^bug', 'bug']
tested by dev team:
 - head-branch: ['^code', 'code']
design approval pending:
 - head-branch: ['^ui', 'ui']
documentation:
 - head-branch: ['^docs', 'docs']