name: shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.2 <4.0.0'

dependency_overrides:
  analyzer: ^5.3.1

dependencies:
  db:
    path: ../db

  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.16.0

