targets:
  $default:
    builders:
      stormberry:
        generate_for:

          # path of model classes
          - lib/src/models/user/user.dart
          - lib/src/models/post/post.dart
          - lib/src/models/story/story.dart
          - lib/src/models/comment/comment.dart