name: db
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: 3.7.2

dependencies:
  stormberry: 0.15.0

dev_dependencies:
  build_runner: 2.4.15
  lints: 5.1.1
  test: 1.25.15
