name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: 3.7.2

dependencies:
  # hashing
  crypt: 4.2.1
  
  # server
  dart_frog: 1.2.0

  # jwt
  dart_frog_auth: 1.2.0
  dart_jsonwebtoken: 3.2.0

  # local
  db:
    path: packages/db

  # local
  shared:
    path: packages/shared

  # ORM
  stormberry: 0.15.0

dev_dependencies:
  mocktail: 1.0.4
  test: 1.25.15
  very_good_analysis: 7.0.0