name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  # hashing
  crypt: ^4.2.1
  
  # server
  dart_frog: ^1.0.0

  # jwt
  dart_jsonwebtoken: ^2.7.1

  # local
  db:
    path: packages/db

  # env
  dotenv: ^4.1.0

  # local
  shared:
    path: packages/shared

  # ORM
  stormberry: ^0.13.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
